name: Merge branch CD
run-name: ${{ github.actor }} ->  ${{ github.event.head_commit.message }}
env: 
  CURRENT_BRANCH: ${{ github.ref_name }}
on:
  push:
    branches:
      - 'dama'
      - 'mihary'
      - 'tino'
jobs:
  merge-branch-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge branch ${{ env.CURRENT_BRANCH }} to develop
        uses: devmasx/merge-branch@1.4.0

        with:
          type: now
          from_branch: ${{ env.CURRENT_BRANCH }}
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Merge branch develop to preprod
        uses: devmasx/merge-branch@1.4.0

        with:
          type: now
          from_branch: develop
          target_branch: preprod
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      env:
        UPSTREAM_URL: "https://github.com/diamondrarktvo/mp3-downloader-prod.git"
        WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        UPSTREAM_BRANCH: "main"
        DOWNSTREAM_BRANCH: ""
        FETCH_ARGS: ""
        MERGE_ARGS: ""
        PUSH_ARGS: ""
